[package]
name = "driver_sgtl5000"
version = "0.1.0"
edition = "2021"
authors = ["Daniël <daniel@hi-squeaky-things.nl>"]
description = "A Rust #no-std optimized wave table synthesizer for embedded devices."
license = "MIT"
repository = "https://github.com/hi-squeaky-things/driver-sgtl5000"
keywords = ["no-std", "i2s", "driver", "sgtl5000"]
categories = ["embedded"]

[dependencies]
embedded-hal = { version = "1.0.0" }

[dev-dependencies]
esp-backtrace = { version = "0.18.1", features = ["panic-handler", "println", "esp32s3"] }
esp-hal = { version = "1.0.0", features = ["esp32s3", "psram"] }
esp-println = { version = "0.16.1", features = ["esp32s3", "log-04"] }

[profile.dev]
opt-level = 1
